title: <p align="center"> Muhammad Saad </p>


logo: "/images/saad1.PNG?raw=true" 

description:
  <p align="center"> 
  <a href="pdf/Muhammad's%20Resume.pdf">Resume</a> | 
  <a href="https://www.linkedin.com/in/muhammad-saad-31740060/">Linkedin</a> |
  <a href="https://github.com/SaadMuhammad">Github</a> | 
  <a href="https://www.credly.com/users/saad-muhammad/badges">Credly</a>
  </p>
 
  <p align="justify">
  I am an IBM certified Data Scientist, Microsoft certified Azure Data Scientist and TensorFlow professional developer.
  <br><br>
  I am currently pursing MS degree in Artificial Intelligence and Data Science from Technische Hochschule Deggendorf and working as BI & data analyst @ Novuter.
  <br><br>
  </p>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
